theme = "serika-dark"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ["goto_next_buffer"]
S-tab = ["goto_previous_buffer"]
A-q = ":buffer-close"

[editor.cursor-shape]
insert = "bar"
normal = "block"
